package main

import (
	"fmt"
	"github.com/jejejery/go-printarray"
	"github.com/jejejery/go-logic/logic1"
	"github.com/jejejery/go-logic/logic2"
	"github.com/jejejery/go-logic/logic3"
	"github.com/jejejery/go-logic/logic4"
)

func main() {
	fmt.Println("=========Logic 1==========")
	logic1_1 := logic1.Logic1_1(10)
	goprintarray.PrintArray(logic1_1)
	fmt.Println("\n")
	logic1_2 := logic1.Logic1_2(10)
	goprintarray.PrintArray(logic1_2)
	fmt.Println("\n")
	logic1_3 := logic1.Logic1_3(10)
	goprintarray.PrintArray(logic1_3)
	fmt.Println("\n")
	logic1_4 := logic1.Logic1_4(10)
	goprintarray.PrintArray(logic1_4)
	fmt.Println("\n")
	logic1_5 := logic1.Logic1_5(10)
	goprintarray.PrintArray(logic1_5)
	fmt.Println("\n")
	logic1_6 := logic1.Logic1_6(10)
	goprintarray.PrintArray(logic1_6)
	fmt.Println("\n")
	logic1_7a := logic1.Logic1_7(10)
	goprintarray.PrintArray(logic1_7a)
	fmt.Println("\n")
	logic1_7b := logic1.Logic1_7(11)
	goprintarray.PrintArray(logic1_7b)
	fmt.Println("\n")
	logic1_8a := logic1.Logic1_8(10)
	goprintarray.PrintArray(logic1_8a)
	fmt.Println("\n")
	logic1_8b := logic1.Logic1_8(11)
	goprintarray.PrintArray(logic1_8b)
	fmt.Println("\n")
	logic1_9a := logic1.Logic1_9(10)
	goprintarray.PrintArray(logic1_9a)
	fmt.Println("\n")
	logic1_9b := logic1.Logic1_9(11)
	goprintarray.PrintArray(logic1_9b)
	fmt.Println("\n")
	logic1_10 := logic1.Logic1_10(10)
	goprintarray.PrintStrArray(logic1_10)
	fmt.Println("\n")
	logic1_11 := logic1.Logic1_11(10)
	goprintarray.PrintStrArray(logic1_11)
	fmt.Println("\n")
	logic1_12 := logic1.Logic1_12(12)
	goprintarray.PrintArray(logic1_12)
	fmt.Println("\n")
	fmt.Println("=========Logic 2==========")
	logic2_1 := logic2.Logic2_1(9)
	goprintarray.PrintMatrix(logic2_1)
	fmt.Println("\n")
	logic2_2 := logic2.Logic2_2(9)
	goprintarray.PrintMatrix(logic2_2)
	fmt.Println("\n")
	logic2_3 := logic2.Logic2_3(9)
	goprintarray.PrintMatrix(logic2_3)
	fmt.Println("\n")
	logic2_4 := logic2.Logic2_4(9)
	goprintarray.PrintMatrix(logic2_4)
	fmt.Println("\n")
	logic2_5 := logic2.Logic2_5(9)
	goprintarray.PrintMatrix(logic2_5)
	fmt.Println("\n")
	logic2_6 := logic2.Logic2_6(9)
	goprintarray.PrintMatrix(logic2_6)
	fmt.Println("\n")
	logic2_7 := logic2.Logic2_7(9)
	goprintarray.PrintMatrix(logic2_7)
	fmt.Println("\n")
	logic2_8 := logic2.Logic2_8(9)
	goprintarray.PrintMatrix(logic2_8)
	fmt.Println("\n")
	logic2_9 := logic2.Logic2_9(9)
	goprintarray.PrintMatrix(logic2_9)
	fmt.Println("\n")
	logic2_10 := logic2.Logic2_10(9)
	goprintarray.PrintMatrix(logic2_10)
	fmt.Println("\n")
	logic2_11 := logic2.Logic2_11(9)
	goprintarray.PrintMatrix(logic2_11)
	fmt.Println("\n")
	logic2_12 := logic2.Logic2_12(9)
	goprintarray.PrintMatrix(logic2_12)
	fmt.Println("\n")
	logic2_13 := logic2.Logic2_13(9)
	goprintarray.PrintMatrix(logic2_13)
	fmt.Println("\n")
	fmt.Println("=========Logic 3==========\n")
	logic3_03 := logic3.Logic3_03(9)
	goprintarray.PrintMatrix(logic3_03)
	fmt.Println("\n")
	// logic3_04 := logic3.Logic3_04(8)
	// goprintarray.PrintMatrix(logic3_04)
	// fmt.Println("\n")
	// logic3_12 := logic3.Logic3_12(9)
	// goprintarray.PrintMatrix(logic3_12)
	// fmt.Println("\n")
	// logic3_13 := logic3.Logic3_13(9)
	// goprintarray.PrintStrMatrix(logic3_13)
	// fmt.Println("\n")
	// logic3_10 := logic3.Logic3_10(8)
	// goprintarray.PrintMatrix(logic3_10)
	// fmt.Println("\n")
	// logic3_14 := logic3.Logic3_14(5)
	// goprintarray.PrintMatrix(logic3_14)
	// fmt.Println("\n")
	fmt.Println("=========Logic 4==========\n")
	logic4_01 := logic4.Logic4_01(4)
	goprintarray.PrintMatrix(logic4_01)
	fmt.Println("\n")
	logic4_02 := logic4.Logic4_02(4)
	goprintarray.PrintMatrix(logic4_02)
	fmt.Println("\n")
	// logic4_03 := logic4.Logic3_03(4)
	// goprintarray.PrintMatrix(logic4_03)
	// fmt.Println("\n")
}